-- Latest congregations table update for login support
-- Adds username and password_hash fields for backend authentication

ALTER TABLE congregations
  ADD COLUMN IF NOT EXISTS username VARCHAR(100),
  ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);

-- Optional: enforce unique usernames if you want login by username to be deterministic
-- Uncomment this after ensuring no duplicate usernames exist
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_congregations_username ON congregations (LOWER(username));

-- Optional backfill example for existing records:
-- UPDATE congregations
-- SET username = LOWER(REPLACE(fullName, ' ', '.'))
-- WHERE username IS NULL OR username = '';

-- Password hashes must be generated by the application using bcrypt.
-- Example (outside SQL): generate hash from the backend when creating/importing users,
-- then store it in password_hash.

-- If your database uses a different naming convention, adjust the column names
-- to match the Go model fields already used in the backend.